### ISSUE TITLE
Add FAQ Questions

### ISSUE THREAD

**Issue by pedersonshrimp** [ShrimpSwap/shrimp-documentation#1]
- When application for CMC and CoinGecko?

**Comment by nikocrypo** [comment]
When audit and why is it taking so long? (beefy explanation? - audit should be done so anyway though, gives more confidence)

**Comment by nikocrypo** [comment]
What will happen to shrimp rewards after Phase 1?

**Comment by nikocrypo** [comment]
What will "integration to ADA, Cardano Blockchain" exactly mean?

**Comment by nikocrypo** [comment]
Whend did you launch? (21st April)

**Comment by nikocrypo** [comment]
How many $SHRIMP are there in total? (Max. 21 Million)

**Comment by pedersonshrimp** [comment]
Fixed with https://github.com/ShrimpSwap/shrimp-documentation/commit/e0663e4c0305069a4c60e67208f3b646ddd4a42f
